version: '3.9'

services:
  worker:
    build: ./worker
    env_file:
      - env_files/worker.env
    networks:
      - rabbitmq_net

  mongo1:
    hostname: mongo1
    container_name: localmongo1
    image: mongo
    restart: always
    environment:
      - MONGO_INITDB_DATABASE=ugc_movies
    expose:
      - "27017"
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - mongo_vol:/data/db
    entrypoint:
      [
        "/usr/bin/mongod",
        "--bind_ip_all",
        "--replSet",
        "rs0",
        "--dbpath",
        "/data/db"
      ]
    networks:
      - mongo_net

  mongosetup:
    image: mongo
    depends_on:
      - mongo1
    volumes:
      - ./mongo/scripts:/scripts
    restart: "no"
    entrypoint: [ "bash", "/scripts/mongo_setup.sh" ]
    networks:
      - mongo_net

  rabbitmq:
    image: rabbitmq:3.11-alpine
    expose:
      - "5672"
    volumes:
      - rabbitmq_vol:/var/lib/rabbitmq/
    networks:
      - rabbitmq_net

  templates_db:
    image: postgres:15.0-alpine
    volumes:
      - templates_data:/var/lib/postgresql/data/
    env_file:
      - env_files/templates_db.env
    environment:
      - POSTGRES_HOST=templates_db
      - POSTGRES_PORT=5432
    expose:
      - "5432"
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "pg_isready -d $$POSTGRES_DB -h $$POSTGRES_HOST -p $$POSTGRES_PORT -U $$POSTGRES_USER"
        ]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  mongo_vol:
  rabbitmq_vol:


networks:
  mongo_net:
